# Generated by Django 5.2.6 on 2025-09-15 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('dz_leader', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='polls_poll_slug_3e2bd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='polls.poll')),
            ],
            options={
                'ordering': ['day'],
                'indexes': [models.Index(fields=['poll', 'day'], name='polls_polld_poll_id_925a88_idx')],
                'unique_together': {('poll', 'day')},
            },
        ),
    ]
