# Generated by Django 5.2.6 on 2025-09-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Informasjon'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_from',
            field=models.DateField(verbose_name='Startdato'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_to',
            field=models.DateField(verbose_name='Sluttdato'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='dz_leader',
            field=models.CharField(max_length=200, verbose_name='Hoppleder'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tittel'),
        ),
    ]
