# Generated by Django 5.2.6 on 2025-09-17 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_description_alter_poll_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=80)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user_cookie', models.CharField(max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nei'), (1, 'Kanskje'), (2, 'Ja')], default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='polls.pollday')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='polls.ballot')),
            ],
            options={
                'indexes': [models.Index(fields=['day', 'status'], name='polls_avail_day_id_0274a2_idx')],
                'unique_together': {('ballot', 'day')},
            },
        ),
    ]
