# Generated by Django 5.2.6 on 2025-09-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_ballot_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Nei'), (1, 'Kanskje'), (2, 'Ja')], null=True),
        ),
    ]
